### ISSUE TITLE
Road Map - Jan 2025

### ISSUE THREAD

**Issue by balaji-sivasakthi** [developer-routes/developer-routes-site#12]
- [x]  Refactor code structure
- [x] Recurive package update using pnpm
- [ ]  need to write e2e and Unit test cased
